services:
  web:
    build: .
    ports:
      - "8501:8501"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - threat-intel-network

  db:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-threats_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - threat-intel-network

volumes:
  postgres_data:

networks:
  threat-intel-network:
    driver: bridge